### ISSUE TITLE
godoc

### ISSUE THREAD

**Issue by pjebs** [go101/gold#1]
How is this different from the `godoc` local webserver functionality that came with go before they removed it?

**Comment by go101** [comment]
The goal of `godoc` is to read docs for exported resource. The goal of `gold` is to read both docs and code. One unfinished goal of `gold` is to also show docs for unexported resource.

Beside the main features listed in readme, `gold` also has some other small different design details from `godoc`:
* list var/const/func all as values together. Yes, functions in go are values actually.
* tag which packages are main packages and provide to link (by clicking the `m`) to corrspoding `main` functions. This is good to start studying a project.
* try to read docs in code. The package details pages only list docs of exported types and values. Other docs, such as package docs can be read directly in code. `gold` tries to make this convenient. For example, we can click the `d` shown before a listed source file to view package docs.
* show a type is being used as parameters/results of which functions.
* show a type has which exported values.

There will be more new small features to be implemented.

**Comment by pjebs** [comment]
What's the point of showing docs for unexpired?

It should also show which version of Go introduced a particular function

**Comment by go101** [comment]
It is "unexported", not "unexpired".

> It should also show which version of Go introduced a particular function

OK, I will add this in todo list.

**Comment by pjebs** [comment]
I meant to unexported (autocorrect). Why do you want to reveal stuff that is not intended to be revealed? I write stuff in my unexported code that is only for my eyes only.

**Comment by go101** [comment]
Because it is good for reading and understanding code sometimes. Gold is helpful to not only using packages, but also understanding the used packages.

**Comment by go101** [comment]
HI, this issue will be closed.

BTW, some new features are added in the latest versions.
