### ISSUE TITLE
package level godoc missing

### ISSUE THREAD

**Issue by jmccormick2001** [go101/gold#2]
question about godoc, in my file, dataprov.go, I have package level godoc like this:

// Package dataprov holds the data provenance logic which is essentially
// used to identify each data source uniquely with a generated ID
// that is passed with all processed data so users can track data back
// to its source
package dataprov

however, when I generate and few the docs for this package I'm not seeing the package godoc
at all...question, is package level godoc text supposed to be present in the generated page?

thanks.

**Comment by go101** [comment]
> is package level godoc text supposed to be present in the generated page?

It is not. 

We can view package docs by clicking the "d->" in front of some listed source code files. This is a deliberate design, as it is recommended to read docs directly in code by the design of Gold.

However, Gold is still in its experimental phase. If many people don't like the design, it can be changed later.

**Comment by jmccormick2001** [comment]
thanks
