### ISSUE TITLE
Cannot run the command: gold: error: cannot open ./...: No such file or directory

### ISSUE THREAD

**Issue by pacoorozco** [go101/gold#4]
Hi,

I've followed the documentation to obtain `gold` using `go get` but once I try to run it I getting some errors:

```
$ export GO111MODULE=on
$ gold std  
gold: error: cannot open std: No such file or directory
$ gold ./...    
gold: error: cannot open ./...: No such file or directory
$ go version    
go version go1.14.7 linux/amd64
```

I'm trying to see documentation of [this package](https://github.com/gphotosuploader/google-photos-api-client-go), v2 branch.

**Can you help me?**

**Comment by go101** [comment]
Could you show the result of `which gold` and `gold -h`?
It looks there is another `gold` program installed in your machine.
If this is true, you can install Gold as other names suggested in the readme file.

**Comment by pacoorozco** [comment]
You were totally right! Another `gold` command was colliding. Thanks!
